# Generated by Django 5.0.4 on 2024-06-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturas', '0004_remove_lectura_mes_lectura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscriptor',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=50, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='suscriptor',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=59, verbose_name='Segundo Nombre'),
        ),
    ]
